{{- if .Values.npd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.npd.config.name }}
  namespace: {{ include "neuron-node-problem-detector-and-recovery.namespace" . }}
  labels:
    {{- include "neuron-node-problem-detector-and-recovery.labels" . | nindent 4 }}
data:
  kernel-monitor.json: |
    {
        "plugin": "kmsg",
        "logPath": "/dev/kmsg",
        "lookback": "5m",
        "bufferSize": 10,
        "source": "kernel-monitor",
        "conditions": [
            {
                "type": "NeuronHealth",
                "reason": "NeuronHasNoError",
                "message": "Neuron has no error"
            }
        ],
        "rules": [
            {
                "type": "permanent",
                "condition": "NeuronHealth",
                "reason": "NeuronHasError_SRAM_UNCORRECTABLE_ERROR",
                "pattern": ".* NEURON_HW_ERR=SRAM_UNCORRECTABLE_ERROR .*"
            },
            {
                "type": "permanent",
                "condition": "NeuronHealth",
                "reason": "NeuronHasError_NC_UNCORRECTABLE_ERROR",
                "pattern": ".* NEURON_HW_ERR=NC_UNCORRECTABLE_ERROR .*"
            },
            {
                "type": "permanent",
                "condition": "NeuronHealth",
                "reason": "NeuronHasError_HBM_UNCORRECTABLE_ERROR",
                "pattern": ".* NEURON_HW_ERR=HBM_UNCORRECTABLE_ERROR .*"
            },
            {
                "type": "permanent",
                "condition": "NeuronHealth",
                "reason": "NeuronHasError_DMA_ERROR",
                "pattern": ".* NEURON_HW_ERR=DMA_ERROR .*"
            },
            {
                "type": "permanent",
                "condition": "NeuronHealth",
                "reason": "NeuronHasError_HANG_ON_COLLECTIVES",
                "pattern": ".* NEURON_HW_ERR=HANG_ON_COLLECTIVES .*"
            }
        ]
    }
{{- end }}