{{- if .Values.npd.enabled }}
{{- if .Values.npd.nodeProblemDetector.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:node-problem-detector
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
    {{- include "neuron-node-problem-detector-and-recovery.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["nodes/status"]
  verbs: ["patch"]
- apiGroups: ["", "events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "neuron-node-problem-detector-and-recovery.fullname" . }}
  namespace: {{ include "neuron-node-problem-detector-and-recovery.namespace" . }}
  labels:
    {{- include "neuron-node-problem-detector-and-recovery.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-problem-detector
subjects:
  - kind: ServiceAccount
    name: {{ include "neuron-node-problem-detector-and-recovery.serviceAccountName" . }}
    namespace: {{ include "neuron-node-problem-detector-and-recovery.namespace" . }}
---
{{- if .Values.npd.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "neuron-node-problem-detector-and-recovery.serviceAccountName" . }}
  namespace: {{ include "neuron-node-problem-detector-and-recovery.namespace" . }}
  labels:
    {{- include "neuron-node-problem-detector-and-recovery.labels" . | nindent 4 }}
  {{- with .Values.npd.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}